### PR TITLE
No update steps

### PR DESCRIPTION
**Pull request by florianjoerg**
## Description
Do also simulation steps if there was no update. Otherwise the simulation steps become inconsistent for further analysis

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by wiederm** [comment]
Is this also ready for review?

**Comment by florianjoerg** [comment]
Yes, should be

**Review by wiederm — APPROVED** [review]
Also looks good to me! Most of this is already in the PBC PR, right? But anyways, this can be merged!

**Comment by florianjoerg** [comment]
Yes, it was not on purpose to have all the pbc commits here as well...

**Pull request merged**
