### PR TITLE
meoh2

### PR DESCRIPTION
**Pull request by florianjoerg**
## Description
Idea: include a second hydrogen on i.e. oxygen for the consideration of possible transfers.
first approach to include second hydrogen in distance calculation for meoh2
## Todos
  - [ ] **Testing!**, is it even doing what we want?
  - [ ] Better integrate this poor man's approach! (Current version just to get it running for this specific case)

## Status
- [ ] Ready to go

---

Die Supersäure gibt ihr Proton an ein Methanol ab. Dieses protonierte Methanol hat dann zwei Wasserstoffe am Sauerstoff, die eigentlich für das Proton hopping gleichberechtigt sein sollten. In der jetzigen Programmversion haben wir bisher aber immer nur die Möglichkeit in Betracht gezogen, dass nur das Wasserstoff wieder abgegeben werden kann, das aus einem Dummy entstanden ist. Dies ist eigentlich auch nicht im Sinne des Grotthus-Mechanismus. Wir haben nun die Idee geboren, dass bei einem Protonentransfer-Event nicht nur die Abstände dieses Wasserstoffes zu potentiellen Akzeptoren überprüft wird, sondern auch der andere Wasserstoff zu seinen entsprechenden potentiellen Akzeptoren.

Beim Transfer wird natürlich wieder nur der Wasserstoff in ein Dummy überführt, der vorher auch ein Dummy war. Eigentlich müsste man in diesem Fall 180° um die OH-Bindung drehen, damit es wieder richtig stimmt, aber dies sollten wir zunächst einmal vernachlässigen. 

---

### CODE REVIEW

**Comment by godenymarta** [comment]
The same should also be done for acetate, both oxygens should be considered for transfer. (Would probably also help us get closer to the experimental transfer times.)

**Comment by godenymarta** [comment]
New idea for proton transfer in general and especially for reorienting molecules:
- Instead of keeping the position of the dummy H after protonation, take the position of the H as it was on the molecule that was deprotonated.
- Update the position of the non-dummy H on MeOH to the old position of the dummy (if equivalent atom used).
- Exchange the positions of the Os in OAc, to keep connectivity to H (if equivalent atom used).

No rotation required, no need to define an axis. However, perhaps still too specific, works only with these small, symmetric molecules.

E.g. in _reorient_atoms:
positions = self.ionic_liquid.simulation.context.getState(getPositions=True.getPositions(asNumpy=True)

atom_idx = candidate.get_idx_for_atom_name(self.ionic_liquid.templates.get_atom_name_for(candidate.current_name))
equivalent_idx = candidate.get_idx_for_atom_name(self.ionic_liquid.templates.get_equivalent_atom_for(candidate.current_name))
pos_atom = positions[atom_idx]
pos_equivalent = positions[equivalent_idx]

positions[atom_idx] = pos_equivalent
positions[equivalent_idx] = pos_atom

self.ionic_liquid.simulation.context.setPositions(positions)

**Comment by florianjoerg** [comment]
What exactly do you mean with the first point? Should this be done in general? how would this work for i.e. Im1-H + Dum-OAc -> Im1-Dum + H-OAc? Wouldn't a bond be artifically elongated?
Second and third point sounds good. Maybe we could use the topology of the atom to adapt the rest of the molecule to the new coordinates? For Dum-OAc, when changing the O's its just adapting the Dum position; if we use topology information it would work for large groups as well...(Could there even be larger groups, which need adaption? Maybe to much overhead for the current stauts, but a future idea)

**Comment by godenymarta** [comment]
My concern is that when changing the dummy atom to a real H, it appears out of nowhere, so theoretically it could be almost on top of something else. Apart from that, the H jumps to the position of the dummy H, which could be more than two bond lengths' distance from its original position. (Although these didn't seem to cause a problem until now.)
But it is true that the "new" bond would be longer than a normal bond to a H. Equilibrium bond lengths are around 0.97 Å (O-H) and 1.00 Å (N-H), that means between 0.92 and 1.06 for a random MeOH I looked at. The new bond would be maximum 1.55 Å long at the start, that is indeed a lot longer. How much of a problem would that be?

retain_H_position

**Comment by florianjoerg** [comment]
I see the point now. We could try this.
I think it would be great to use a new, different PR for this new transfer method and use this current PR seperately for the inclusion of the additional alternative atom. Just so that it is easier to track the changes coming from each adjustment.
Would be great if you could start this new PR, @godenymarta. Thanks!
There we should also think a bit more in detail how to achieve the new transfer method. But probably this works alongside coding;)

**Comment by florianjoerg** [comment]
Closed in favor of #57

**Pull request closed without merging**
